### ISSUE TITLE
errors on install, unresolved external symbol ...

### ISSUE THREAD

**Issue by jeremydchambers** [planetbeing/foscam-binary-client#1]
I'm getting errors during the install process. Any help would be appreciated. I'm on Windows 10.

C:\Users\jerem>npm install -g foscam-binary-client

> foscam-binary-client@0.2.1 install C:\Users\jerem\AppData\Roaming\npm\node_modules\foscam-binary-client
> node-gyp rebuild

C:\Users\jerem\AppData\Roaming\npm\node_modules\foscam-binary-client>if not defined npm_config_node_gyp (node "C:\Users\jerem\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cpp
  win_delay_load_hook.cc
  g72x.c
  g726_16.c
  g726.c
     Creating library C:\Users\jerem\AppData\Roaming\npm\node_modules\foscam-binary-client\build\Release
  \FoscamG726.lib and object C:\Users\jerem\AppData\Roaming\npm\node_modules\foscam-binary-client\build\
  Release\FoscamG726.exp
g72x.obj : error LNK2001: unresolved external symbol linear2ulaw [C:\Users\jerem\AppData\Roaming\npm\nod
e_modules\foscam-binary-client\build\FoscamG726.vcxproj]
g72x.obj : error LNK2001: unresolved external symbol ulaw2linear [C:\Users\jerem\AppData\Roaming\npm\nod
e_modules\foscam-binary-client\build\FoscamG726.vcxproj]
g72x.obj : error LNK2001: unresolved external symbol alaw2linear [C:\Users\jerem\AppData\Roaming\npm\nod
e_modules\foscam-binary-client\build\FoscamG726.vcxproj]
g72x.obj : error LNK2001: unresolved external symbol linear2alaw [C:\Users\jerem\AppData\Roaming\npm\nod
e_modules\foscam-binary-client\build\FoscamG726.vcxproj]
C:\Users\jerem\AppData\Roaming\npm\node_modules\foscam-binary-client\build\Release\FoscamG726.node : fat
al error LNK1120: 4 unresolved externals [C:\Users\jerem\AppData\Roaming\npm\node_modules\foscam-binary-
client\build\FoscamG726.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\jerem\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\jerem\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jerem\AppData\Roaming\npm\node_modules\foscam-binary-client
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\jerem\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "foscam-binary-client"
npm ERR! node v6.7.0
npm ERR! npm  v4.0.1
npm ERR! code ELIFECYCLE

**Comment by MystK** [comment]
Hello! This is happening to me as well!
